version: '3.4'

services:
  postgisdb:
    image: kartoza/postgis:13.0
  pgadmin:
    image: dpage/pgadmin4

  microworkertest:
    image: ${DOCKER_REGISTRY-}microworkertest
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  postgres_data:
  pgadmin_data: